### ISSUE TITLE
Функция ExecuteQueryMapping<T> работает не корректно

### ISSUE THREAD

**Issue by kdolganin** [ilyabreev/ClickHouse.Net#1]
В функции нет преобразования типов при получении данных из ClickHouse. Например если свойство в принимающем объекте имеет тип Guid, то получая из ClickHouse данные типа String возникает исключение.

**Comment by kdolganin** [comment]
Такая же беда и с функцией BulkInsert<T>

**Comment by ilyabreev** [comment]
Совершенно верно. В них пока нет разумной логики по типам. Приветствуются PR :-)

**Comment by kdolganin** [comment]
куда можно в личку написать?

**Comment by ilyabreev** [comment]
tg @ilyabreev

**Comment by ilyabreev** [comment]
Исправлено в #2. Выйдет в 0.5.0.
