### ISSUE TITLE
TCP over HTTP advantages

### ISSUE THREAD

**Issue by Astimus** [ilyabreev/ClickHouse.Net#12]
Hi. I'm sorry for asking the question here.
What are the advantages of `TCP` over the `HTTP` `ClickHouse `interface? (performance, reliability, security, maintainability, support of different formats like parquet and arrow, streaming support)
As I understand, It is much harder to support Native format and interface because of lack of specification. Most likely, `Apache Parquet`+ `HTTP` does not lose in speed to the native interface. 
Why have you decided to implement the library on the native interface? Thank you in advance.

**Comment by ilyabreev** [comment]
Hi. It's totally ok that you asking.

First of all, I didn't think about advantages or disadvantages of `TCP` before I started this lib. There was `ClickHouse.Ado` package that provides some API and it was missing some convenient methods. From my point of view: I need some useful API and I wrap `ClickHouse.Ado` to provide it.

When we talk about `TCP` over `HTTP` advantages in general it's not so much about speed but smaller network footprint I think.

**Comment by Astimus** [comment]
@ilyabreev thank you for immediate response.
