### ISSUE TITLE
sir,how I can make it work?

### ISSUE THREAD

**Issue by 564064202** [ilyabreev/ClickHouse.Net#5]
I can use dbeaver with (host ,port ,dbname) just like below
![image](https://user-images.githubusercontent.com/12368358/66555791-cfbba300-eb81-11e9-8eca-f3948f52ffd6.png)
but I don't know why you must use 
Compress=True;CheckCompressedHash=False;Compressor=lz4;Host=192.168.0.163;Port=9000;User=default;
so  I don't know how to  make it work

**Comment by ilyabreev** [comment]
`Compress=True;CheckCompressedHash=False;Compressor=lz4;Host=192.168.0.163;Port=9000;User=default;` is .NET connection string to ClickHouse instance.

All you need is `Host` - your instance hostname or IP and `Port` if your port is non-default.

**Comment by 564064202** [comment]
System.IO.IOException:“Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.”
------
 static string str = "Host=10.255.52.64;Port=8123;Database=default;";

**Comment by 564064202** [comment]
@ilyabreev

**Comment by ilyabreev** [comment]
Maybe it'll be better to ask your question at http://stackoverflow.com?

**Comment by ilyabreev** [comment]
If you have a bug report or feature proposal please let me know.
