### ISSUE TITLE
Invalid result of ClickHouseDatabase.TableExists method

### ISSUE THREAD

**Issue by freem-trg** [ilyabreev/ClickHouse.Net#6]
Reproduction:
1) Create default connection with clickhouse (connectionSettings.Database = "default")
2) Then call database.ChangeDatabase( "someDatabase" );
3) Then call database.TableExists( "existingTable" ). It will check `default.existingTable` instead of `someDatabase.existingTable` because of [link](https://github.com/ilyabreev/ClickHouse.Net/blob/755d87ea65fa294033b9208e33633a21125cd519/src/ClickHouse.Net/ClickHouseDatabase.cs#L97)

I think there should be:
` cmd.AddParameter("database", _connection.Database);`
instead of
` cmd.AddParameter("database", _connectionSettings.Database);`

Or i'm missing something?

**Comment by AntonAlekseevAA** [comment]
Hello, thanks for you response. I fix it and create pull request, but if you want, i close it and you can open it youself, because i only repeat you code.

**Comment by freem-trg** [comment]
Thank you! It's ok. Your pull request will be enough

**Comment by ilyabreev** [comment]
@freem-trg Thanks for reporting this issue!
@AntonAlekseevAA Thanks for the fix man!
